twproject/twapp/urls.py
from django.conf.urls import url
from . import views
from .forms import LoginForm

urlpatterns = [

    url(r'^$', views.index, name='index'),

    # Signup
    url(r'^register/$', views.register, name="register"),

    # Login
    url(r'^login/$', 'django.contrib.auth.views.login', 
        {'authentication_form': LoginForm}, name='login'),

    # Logout
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'registration/logout.html'},
         name='logout_user'),

    # Posting
    url(r'^post/$', views.posting_form, name='posting_form'),

    # Member URL View Routes
    url(r'^members/$', views.member_list, name="member_list"),
    url(r'^member_tweets/(?P<id>\d+)/$', views.member_tweets, name="member_tweets"),

    # Tweet URL View Routes
    url(r'^tweets/$', views.tweet_list, name='tweet_list'),

]

twproject/twproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('twapp.urls', namespace='twapp')),
]

twproject/twapp/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
import datetime

# Define Tag, Tweet, and Member data models.

# TAGS ARE A BONUS REQUIREMENT
# DON'T DO UNTIL OTHERS ARE DONE
"""
class Tag(models.Model):
    text = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.text
"""

class Member(models.Model):
    account = models.OneToOneField(User)

    def __str__(self):
        return self.account.username

    def get_absolute_url(self):
        return reverse('members:member_detail', kwargs={'id': self.pk})


class Tweet(models.Model):
    memb = models.ForeignKey('Member')
    msg = models.TextField(max_length=140)
    date = datetime.datetime.now()
    # tags = models.ForeignKey('Tag')

    def __str__(self):
        return '{}    {}'.format(self.memb, self.msg)
    
    def get_absolute_url(self):
        return reverse('tweet:tweet_detail', args=[self.pk])

twproject/twapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User 
from django import forms
from .models import Member, Tweet

# Form for posting a message 'tweet'.
class PostingForm(forms.ModelForm):
    msg = forms.CharField(max_length=140)
    
    class Meta:
        model = Tweet
        fields = ('msg',)


# User Login.
class LoginForm(AuthenticationForm):
    pass

# User Registration.
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password2',)


    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

twproject/twapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import PostingForm, LoginForm, UserRegistrationForm

# Import the music app models.
from .models import Member, Tweet

def index(request):
    return render(request, 'twapp/index.html')

# Member data views
def member_list(request):
    members = Member.objects.all()

    context = {
        "members": members,
    }

    return render(request, "twapp/member_list.html", context)

def member_tweets(request, id):
    member = Member.objects.filter(id=id)
    tweets = Tweet.objects.filter(memb=id)

    context = {
        "member":member,
        "tweets":tweets
    }
    
    return render(request, 'twapp/member_tweets.html', context)


# Tweet data views
def tweet_list(request):
    tweets = Tweet.objects.all()
    
    context = {
        "tweets": tweets,
    }

    return render(request, "twapp/tweet_list.html", context)


def login_form(request):
    return render(request, "registration/login.html")


def logout_user(request):
    logout(request)
    return redirect('index.html')

@login_required
def posting_form(request):
    
    if request.method == "POST":
        form = PostingForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.memb = request.user.member
            #import pdb;pdb.set_trace()
            tweet.save()

            return redirect('twapp:member_tweets', id=request.user.member.id)
    else:
        form=PostingForm()

    context = {
        "form": form,
    }

    return render(request, 'twapp/posting_form.html', context)


def register(request):
    if request.method== "POST":
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            new_account = form.save(commit=False)
            new_account.set_password(form.cleaned_data["password"])
            new_account.save()
            member = Member()
            member.account = new_account
            member.save()

            return redirect('twapp:member_tweets', member.id)

    else:
        form = UserRegistrationForm()

    context = {
        "form": form
    }

    return render(request, 'registration/register.html', context)

twproject/twapp/templates/twapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            T W A P P - Twitter Clone with Django
        {% endblock title %}
    </title>

    <!-- Per BS Mobile Viewport recomendation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Exo+2|Lato" rel="stylesheet">
    
    <!-- TWAPP Style Rules -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-fixed-top">
              <div class="container-fluid topnav">
                <div class="navbar-header">

                    <a href="/"><img class="navbar-brand logo" src="{% static 'images/awesome_tweet.png' %}"></a>

                    <ul class="nav navbar-nav navbar-right">

                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'twapp:posting_form' %}">Create Post</a></li>
                        <li><a href="{% url 'twapp:member_tweets' request.user.id %}">My Posts</a></li>
                        <li><a href="{% url 'twapp:member_list' %}">Users</a></li>
                        <li><a href="{% url 'twapp:logout_user' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'twapp:member_list' %}">Users</a></li>
                        <li><a href="{% url 'twapp:register' %}">Signup</a></li>
                        <li><a href="{% url 'twapp:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
              </div>
            </nav>

        {% block jumbo %}

        {% endblock %}
        </header>
        
        {% block content %}

        {% endblock %}

    </div> <!--  End div class container-fluid -->

    <footer class="page-footer">
        <div class="container-fluid">
            <p>Twitter Clone Prject | &copy; 2016 Brett Fraley</p>
        </div>
    </footer>

    <!-- Jquery / Bootstrap JS -->
    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <!-- JS For this project -->


</body>
</html>

twproject/twapp/templates/twapp/index.html
{% extends "twapp/base.html" %}

{% block jumbo %}
    <div class="jumbotron">
        <h1>T W A P P</h1> 
        <p>twitter clone project</p>
        <p><a href="{% url 'twapp:register' %}" class="btn btn-success btn-lg">Sign Up!</a></p>
    </div>
{% endblock jumbo %}


{% block content %}


{% endblock content %}

twproject/twapp/templates/twapp/login_form.html
<!-- twapp/templates/twapp/login_form.html -->

{% extends "twapp/base.html" %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Login</h2>
    </div>
  
    <div class="panel-body">

        {% if form.errors %}
        <div class="alert alert-danger">Invalid login. Try Again.</div>
        {% endif %}

        <form action="{% url 'twapp:member_list' %}" method="post">
        {% csrf_token %}
            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1">Username</span>
                <input type="text" class="form-control" placeholder="" aria-describedby="sizing-addon1">
            </div>

            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1">Password</span>
                <input type="text" class="form-control" placeholder="" aria-describedby="sizing-addon1">
            </div>
            
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
    </div>
</div>

{% endblock content %}

twproject/twapp/templates/twapp/member_list.html
<!-- twapp/templates/twapp/member_list.html -->

{% extends "twapp/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="main-content">
    <h1>Twapp Users</h1>

{% for member in members %}
    <div class="panel panel-info">
      <!-- Default panel contents -->
      <div class="panel-body">
        <img class ="profile-pic" src="{% static 'images/awesome_profile.png' %}">
        <a href="{% url 'twapp:member_tweets' member.id%}"><h2>{{member.account.username}}</h2></a>
      </div>
    </div>
{% endfor %}

</div> <!-- end main content -->
{% endblock content %}

twproject/twapp/templates/twapp/member_tweets.html
<!-- twapp/templates/twapp/member_tweets.html -->

{% extends "twapp/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="main-content">

    {% for tweet in tweets %}
    <div class="panel panel-info">
        <!-- Default panel contents -->
        <div class="panel-heading">
        {{tweet.memb.account.username}} | {{tweet.date}}</div>
        <div class="panel-body">
        <img class ="profile-pic" src="{% static 'images/awesome_profile.png' %}">
            <p>{{tweet.msg}}</p>
        </div>
    </div>
    {% endfor %}

</div> <!-- end main content -->
{% endblock content %}

twproject/twapp/templates/twapp/posting_form.html
<!-- twapp/templates/twapp/posting_form.html -->

{% extends "twapp/base.html" %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">New Post</h2>
    </div>
  
    <div class="panel-body">

        <form action="" method="post">
        {% csrf_token %}

            <div class="input-group input-group-lg">
            {{form}}
            </div>

            <button class="btn btn-primary" type="submit">Ok</button>
        </form>
    </div>
</div>

{% endblock content %}

twproject/twapp/templates/twapp/tweet_list.html
<!-- twapp/templates/twapp/tweet_list.html -->

{% extends "twapp/base.html" %}

{% block content %}
<div class="main-content">
    <h1>All Posts</h1>

  {% for tweet in tweets %}
  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">{{tweet.memb}} | {{tweet.date}}</div>
    <div class="panel-body">
        <p>{{tweet.msg}}</p>
    </div>
    
  </div>
  {% endfor %}

</div> <!-- end main content -->
{% endblock content %}